# Default values for alcyon-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  replicaCount: 1
  eksVersion: "1.24"
  usealb: true
  environmentName: "uat-nz-wk"
  image:
    registry: dockerp.rtsprod.net
    pullPolicy: Always
    pullSecret: regsecret
  environment: production
  ingress:
    class: "nginx"
    webDomain: uat.redflexnz.onl
    serviceDomain: alc-api.uat.redflexnz.onl
    serviceDomainALB: alc-api-alb.uat.redflexnz.onl
    photonoticeDomainWA: photonotice.uat.redflexnz.onl
    sidekiqDomain: sidekiq.uat.redflexnz.onl
    armDomain: arm.uat.redflexnz.onl
  publicIngress:
    class: "public-ingress-nginx"
    serviceDomain: alcyonapi.uat.redflexnz.onl
    serviceDomainALB: alcyonapi-api.uat.redflexnz.onl
  publicSubnets: subnet-037dceb7bf159a83d,subnet-0bd7652973b1deb31  
  certificateARN:  arn:aws:acm:ap-southeast-2:774407230214:certificate/79cda981-6a1b-4dcd-87b9-93b435500cbb
  minioEnabled: "false"
  activeSpringProfile: Production
  db:
    host: uat-nz-wk-alcyon-backoffice-rds.uat.redflexnz.onl
    port: 5432
    allowCIDR:
      - 10.146.11.0/24
      - 10.146.12.0/24
      - 10.146.13.0/24
  reports:
    db:
      host: uat-nz-wk-alcyon-backoffice-report-rds.uat.redflexnz.onl
      port: 5432
      allowCIDR:
        - 10.146.11.0/24
        - 10.146.12.0/24
        - 10.146.13.0/24
  sqs:
    allowCIDR: #SQS VPC endpoint IP
      - 10.146.1.0/24
      - 10.146.2.0/24
      - 10.146.3.0/24
  kafka:
    allowCIDR:
      - 10.146.11.0/24
      - 10.146.12.0/24
      - 10.146.13.0/24
    port: 9096
  loadBalancer:
    allowCIDR:
      - 10.146.1.0/24
      - 10.146.2.0/24
      - 10.146.3.0/24
      - 10.146.101.0/24
      - 10.146.102.0/24
  internalLB:
    allowCIDR:
      - 10.146.1.0/24
      - 10.146.2.0/24
      - 10.146.3.0/24
  s3:
    region: us-west-2
    allowCIDR:
      # curl -L https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes[] | select(.service=="S3" and .region=="ap-southeast-2") | .ip_prefix'
      - 52.95.128.0/21
      - 3.5.164.0/22
      - 3.5.168.0/23
      - 3.26.88.0/28
      - 3.26.88.16/28
  elasticsearch:
    protocol: https
    host: "vpc-uat-nz-wk-logs-es-77uq5vqkjtlocyby67yc4a26c4.ap-southeast-2.es.amazonaws.com"
    allowCIDR:
      - 10.146.1.0/24
      - 10.146.2.0/24
      - 10.146.3.0/24
    port: 443
  nginx:
    allowCIDR:
      - 10.146.0.0/16
      - 172.20.0.0/16
      - 172.21.0.0/16
  falcon:
    allowCIDR:
      - 35.160.117.193
      - 52.43.192.139
      - 54.187.226.134
  okta:
    allowCIDR:
      - 0.0.0.0/0 # TODO: restrict if Okta has published public IP range.
  mongo:
    host: "uat-nz-wk-alcyon-migration-docdb.uat.redflexnz.onl"
    username: mongo
    ssl: false
    port: 27017
    database: instigator
    allowCIDR:
      - 10.146.11.0/24
      - 10.146.12.0/24
      - 10.146.13.0/24
  redis:
    url: redis://uat-nz-wk-alcyon-migration-redis.uat.redflexnz.onl:6379/0
    allowCIDR:
      - 10.146.11.0/24
      - 10.146.12.0/24
      - 10.146.13.0/24
  onPremDB:
    host: "172.31.4.111"
    port: "1521"
    database: "qaapp.qatest.redflex.com"
    username: "READ_ONLY"
    allowCIDR:
      - 172.31.4.0/24
  ec2Metadata:
    allowCIDR: 169.254.169.254/32
  route53:
    allowCIDR: 0.0.0.0/0
    port: 443
  kubeApiServerPodCIDR: #TODO: Replace the below value with EKS cluster subnets CIDR Ranges
    - 10.146.0.0/16
  kubeApiServerPodPort: 443
  baseNamespace: base
  baseReleaseName: base-release
  monitoringNamespace: monitoring
  applicationNamespace: alcyon-app
  alcyoncontrolNamespace: alcyon-control
  utilityNamespace: utility
  armNamespace: arm
  alcyonExpressNamespace: alcyon-express
  stubNamespace: stub
  nzNamespace: upgrade
