# Default values for alcyon-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  replicaCount: 1
  eksVersion: "1.22"
  image:
    registry: dockerp.rtsprod.net
    pullPolicy: Always
    pullSecret: regsecret
  environment: production
  ingress:
    class: "nginx"
    webDomain: stg.redflexnt.onl
    serviceDomain: alc-api.stg.redflexnt.onl
    photonoticeDomainWA: photonotice.stg.redflexnt.onl
    sidekiqDomain: sidekiq.stg.redflexnt.onl
    armDomain: arm.stg.redflexnt.onl
  publicIngress:
    class: "public-ingress-nginx"
    serviceDomain: alcyonapi.stg.redflexnt.onl
  minioEnabled: "false"
  activeSpringProfile: Production
  db:
    host: stg-au-nt-alcyon-backoffice-rds.stg.redflexnt.onl
    port: 5432
    allowCIDR:
      - 10.136.11.0/24
      - 10.136.12.0/24
      - 10.136.13.0/24
  reports:
    db:
      host: stg-au-nt-alcyon-backoffice-report-rds.stg.redflexnt.onl
      port: 5432
      allowCIDR:
        - 10.136.11.0/24
        - 10.136.12.0/24
        - 10.136.13.0/24
  sqs:
    allowCIDR: #SQS VPC endpoint IP
      - 10.136.1.0/24
      - 10.136.2.0/24
      - 10.136.3.0/24
  kafka:
    allowCIDR:
      - 10.136.11.0/24
      - 10.136.12.0/24
      - 10.136.13.0/24
    port: 9096
  loadBalancer:
    allowCIDR:
      - 10.136.1.0/24
      - 10.136.2.0/24
      - 10.136.3.0/24
  internalLB:
    allowCIDR:
      - 10.33.4.212/32
      - 10.35.5.65/32
  s3:
    region: us-west-2
    allowCIDR:
      # curl -L https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes[] | select(.service=="S3" and .region=="ap-southeast-2") | .ip_prefix'
      - 52.95.128.0/21
      - 3.5.164.0/22
      - 3.5.168.0/23
      - 3.26.88.0/28
      - 3.26.88.16/28
  elasticsearch:
    protocol: https
    host: "vpc-stg-au-nt-logs-es-qicabpa2vf7nb5rwr5zbtb2yom.ap-southeast-2.es.amazonaws.com"
    allowCIDR:
      - 10.136.1.0/24
      - 10.136.2.0/24
      - 10.136.3.0/24
    port: 443
  nginx:
    allowCIDR:
      - 10.136.0.0/16
      - 172.20.0.0/16
      - 172.21.0.0/16
  falcon:
    allowCIDR:
      - 35.160.117.193
      - 52.43.192.139
      - 54.187.226.134
  okta:
    allowCIDR:
      - 0.0.0.0/0 # TODO: restrict if Okta has published public IP range.
  mongo:
    host: "stg-au-nt-alcyon-migration-docdb.stg.redflexnt.onl"
    username: mongo
    ssl: false
    port: 27017
    database: instigator
    allowCIDR:
      - 10.136.11.0/24
      - 10.136.12.0/24
      - 10.136.13.0/24
  redis:
    url: redis://stg-au-nt-alcyon-migration-redis.stg.redflexnt.onl:6379/0
    allowCIDR:
      - 10.136.11.0/24
      - 10.136.12.0/24
      - 10.136.13.0/24
  onPremDB:
    host: "10.136.2.109"
    port: "1524"
    database: "XE"
    username: "IIPS_NT_DT"
    schema: "IIPS_NT_DT"
    allowCIDR:
      - 10.136.2.109/32
  ec2Metadata:
    allowCIDR: 169.254.169.254/32
  route53:
    allowCIDR: 0.0.0.0/0
    port: 443
  kubeApiServerPodCIDR: #TODO: Replace the below value with EKS cluster subnets CIDR Ranges
    - 10.136.0.0/16
  kubeApiServerPodPort: 443
  baseNamespace: base
  baseReleaseName: base-release
  monitoringNamespace: monitoring
  applicationNamespace: alcyon-app
  utilityNamespace: utility
  migrationNamespace: migration
  armNamespace: arm
  stubNamespace: stub
  ntNamespace: au-nt

