# Default values for alcyon-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  replicaCount: 1
  eksVersion: "old"
  usealb: false
  image:
    registry: dockerp.rtsprod.net
    pullPolicy: IfNotPresent
    pullSecret: regsecret
  environment: production
  ingress:
    class: "nginx"
    webDomain: redflexusa.onl
    serviceDomain: alc-api.canyon.redflexusa.onl
    photonoticeDomain: alcyon.photonotice.com
    wizardDomain: wizard.canyon.redflexusa.onl
    sidekiqDomain: sidekiq.canyon.redflexusa.onl
    armDomain: arm.canyon.redflexusa.onl
    ipaprocessrDomain: ipaprocessr.redflexusa.onl
  publicIngress:
    class: ""
    serviceDomain: alcyonapi.redflex.com
  minioEnabled: "false"
  activeSpringProfile: Production
  reports:
    db:
      host: 172.20.90.160
      port: 5432
      allowCIDR:
        - 172.20.90.160/32
  db:
    host: alcyon-canyon-aur-db-5-cluster.cluster-cwcu3y67yidj.us-gov-west-1.rds.amazonaws.com
    port: 5432
    allowCIDR:
      - 10.202.11.0/24
      - 10.202.12.0/24
      - 10.202.13.0/24
  sqs:
    allowCIDR: #SQS VPC endpoint IP
      - 10.202.1.109/32
      - 10.202.2.222/32
      - 10.202.3.131/32
  loadBalancer:
    allowCIDR:
      - 10.202.1.0/24
      - 10.202.2.0/24
      - 10.202.3.0/24
  internalLB:
    allowCIDR:
      - 10.202.1.46/32
      - 10.202.2.56/32
      - 10.202.3.34/32
  kafka:
    allowCIDR:
      - 10.202.11.0/24
      - 10.202.12.0/24
      - 10.202.13.0/24
    port: 9096
  s3:
    # curl -L https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes[] | select(.service=="S3" and .region=="us-gov-west-1") | .ip_prefix'
    region: us-gov-west-1
    allowCIDR:
      - 0.0.0.0/0 # Need to communicate to us-west-2 and us-east-1 for FS.
  ssm:
    allowCIDR:
      - 0.0.0.0/0 # Need to communicate to us-west-2 and us-east-1 for FS.    
  elasticsearch:
    protocol: https
    host: "vpc-logs-us-gov-west-1-dvi3yoxfxbj2kjad7fnph3frsy.us-gov-west-1.es.amazonaws.com"
    allowCIDR:
      - 10.202.1.0/24
      - 10.202.2.0/24
      - 10.202.3.0/24
    port: 443
  nginx:
    allowCIDR:
      - 10.202.0.0/16
      - 172.21.0.0/16
      - 172.22.0.0/16
  falcon:
    allowCIDR:
      - 35.160.117.193
      - 52.43.192.139
      - 54.187.226.134
  okta:
    allowCIDR:
      - 0.0.0.0/0 # TODO: restrict if Okta has published public IP range.
  ec2Metadata:
    allowCIDR: 169.254.169.254/32
  route53:
    allowCIDR: 0.0.0.0/0
    port: 443
  mongo:
    host: "alcyon-canyon-archive2-db.cluster-cwcu3y67yidj.us-gov-west-1.docdb.amazonaws.com"
    port: 27017
    ssl: false
    database: instigator
    username: mongo
    allowCIDR:
      - 10.202.11.0/24
      - 10.202.12.0/24
      - 10.202.13.0/24
  redis:
    url: redis://alcyon-canyon-redis-db.dfj9gu.ng.0001.usgw1.cache.amazonaws.com:6379/0
    allowCIDR:
      - 10.202.11.0/24
      - 10.202.12.0/24
      - 10.202.13.0/24
  onPremDB:
    host: "192.168.101.112"
    port: "1521"
    database: "rfprod"
    username: "READ_ONLY"
    allowCIDR:
      - 192.168.101.0/24
  kubeApiServerPodCIDR: #TODO: Replace the below value with EKS cluster subnets CIDR Ranges
    - 10.202.0.0/16
  kubeApiServerPodPort: 6443
  baseNamespace: base
  baseReleaseName: base-release
  monitoringNamespace: monitoring
  applicationNamespace: alcyon-app
  utilityNamespace: utility
  migrationNamespace: migration
  armNamespace: arm
  usNamespace: alcyon-app
  configserver:
    useLocalFile: false
    retry:
      maxAttempts: 4
    rest:
      domain: http://configstore.utility
      username: ''
      password: ''
    cache:
      evictFrequency: 300000
      enableEviction: false