apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  minReadySeconds: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
        env: {{ .Values.global.environment }}
        tier: {{ .Values.tier }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.name }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.global.image.registry }}/trinity/submittr:{{ .Values.imageTag }}"
        resources:
          requests:
            memory: "300Mi"
            cpu: "20m"
          limits:
            memory: "5Gi"
            cpu: "800m"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.global.activeSpringProfile }}
        - name: SUBMITTR_DEFAULTTIMEZONE
          value: {{ .Values.defaultTimezone | quote }}
        - name: SUBMITTR_ALCYON_REST_DOMAIN
          value: {{ .Values.alcyon.rest.domain | quote }}
        - name: SUBMITTR_ALCYON_REST_USERNAME
          value: {{ .Values.alcyon.rest.username | quote }}
        - name: SUBMITTR_ALCYON_REST_ENDPOINTS_MEDIAUPDATEURL
          value: {{ .Values.alcyon.rest.endpoints.mediaUpdateURL | quote }}  
        - name: SUBMITTR_ALCYON_REST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: au-wa-secret
              key: SUBMITTR_ALCYON_PASSWORD
        - name: S3_REGION
          value: {{ .Values.s3.region | quote }}
        - name: S3_MEDIABUCKETNAME
          value: {{ .Values.s3.mediaBucketName | quote }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 30
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 30
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}


