apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: submittr
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{ range $index,$cidrRange := .Values.global.loadBalancer.allowCIDR }}
        - ipBlock:
            cidr: {{ $cidrRange }}
        {{ end }}
      ports:
        - port: 8080
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app: alcyon
          namespaceSelector:
            matchLabels:
              name: {{ .Values.global.applicationNamespace }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: alcyon-bg
          namespaceSelector:
            matchLabels:
              name: {{ .Values.global.applicationNamespace }}
      ports:
        - protocol: TCP
          port: 8080
    - to:
        {{ range $index,$cidrRange := .Values.global.s3.allowCIDR -}}
        - ipBlock:
            cidr:  {{ $cidrRange}}
        {{ end }}
      ports:
        - protocol: TCP
          port: 443

    - to:
        - ipBlock:
            cidr: {{ .Values.global.ec2Metadata.allowCIDR }}
      ports:
        - protocol: TCP
          port: 80

