kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    tier: {{ .Values.tier }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeSpringProfile }}
  REFERENCR_ALCYON_REST_DOMAIN: {{ .Values.alcyon.domain }}
  REFERENCR_ALCYON_REST_USERNAME: {{ .Values.alcyon.username }}
